# github.com/<USER>/<REPO>
# <USER>.github.io/<REPO>/
owner: rapidcow   # <USER>
repo: upptime     # <REPO>

sites:
  - name: 'www [dot] rapidcow.org'
    url: https://www.rapidcow.org/
    slug: www-rapidcow-org
  - name: status.rapidcow.org
    url: https://status.rapidcow.org/
  - name: foss.rapidcow.org
    url: https://foss.rapidcow.org/
  - name: ftp.rapidcow.org
    url: https://ftp.rapidcow.org/pub/lib/perl5/List-Search-0.3_1.tar.gz
  - name: ns1.rapidcow.net
    url: https://ns1.rapidcow.net/
  - name: ns2.rapidcow.net
    url: https://ns2.rapidcow.net/
  - name: school site (blegh)
    url: https://www.endfindme.com/
    slug: school-site
  - name: CS school site
    url: https://pages.cs.wisc.edu/~emeng/
  - name: neocities
    url: https://rapidcow.neocities.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rapidcow's Upptime test
  introTitle: |
    Uptime please
  introMessage: |
    it's just uptime. nothing to see here. it's not like i serve anybody, do i?

    I do *real* updates at [status.rapidcow.org](https://status.rapidcow.org/).
    All you'll see here are numbers.  But if that's what you're into, sure...
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
